Repository CS3219-SE-Principles-and-Patterns/cs3219-project-ay2122-2122-s1-g3, pull requests merged in 2021-11, with the labels that each got.

#49 Add env variables for frontend connection
  .github/workflows/node.js.yml
  frontend/src/Room/editor.js
  frontend/src/Room/video.js
  frontend/src/Screen/Home.js
  frontend/src/Screen/Login.js
  frontend/src/Screen/Signup.js
Labels: bug

#50 Create kubernetes files for all microservices
  backend/compiler-deployment.yml
  backend/compiler-service.yml
  backend/editor-configure-map.yml
  backend/editor-deployment.yml
  backend/editor-redis-deployment.yml
  backend/editor-redis-service.yml
  backend/editor-service.yml
  backend/editor/package-lock.json
  backend/editor/package.json
  backend/editor/server.js
  backend/frontend-configure-map.yml
  backend/frontend-deployment.yml
  backend/frontend-service.yml
  backend/matchmaking-deployment.yml
  backend/matchmaking-service.yml
  backend/video-configure-map.yml
  backend/video-deployment.yml
  backend/video-redis-deployment.yml
  backend/video-redis-service.yml
  backend/video-service.yml
  backend/video/package-lock.json
  backend/video/package.json
  backend/video/server.js
Labels: Feature

#57 Check for email validity
  frontend/src/Screen/Login.js
  frontend/src/Screen/Signup.js
Labels: Frontend
